calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/CalloutEngineSetting__mdt.object-meta.xml
<CustomObject>
    <label>Callout Engine Setting</label>
    <pluralLabel>Callout Engine Settings</pluralLabel>
</CustomObject>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/APIKeyToken__c.field-meta.xml
<CustomField>
    <fullName>APIKeyToken__c</fullName>
    <label>API Key: Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/APIKeyTokenPlacement__c.field-meta.xml
<CustomField>
    <fullName>APIKeyTokenPlacement__c</fullName>
    <label>API Key: Token Placement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Endpoint</fullName>
                <default>true</default>
                <label>Endpoint</label>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/AuthenticationType__c.field-meta.xml
<CustomField>
    <fullName>AuthenticationType__c</fullName>
    <label>Auth Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple</fullName>
            </value>
            <value>
                <fullName>API Key</fullName>
            </value>
            <value>
                <fullName>Basic</fullName>
                <default>true</default>
                <label>Basic</label>
            </value>
            <value>
                <fullName>Bearer</fullName>
            </value>
            <value>
                <fullName>OAuth</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Override</fullName>
                <isActive>false</isActive>
                <label>Override</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/BasicPassword__c.field-meta.xml
<CustomField>
    <fullName>BasicPassword__c</fullName>
    <label>Basic: Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/BasicToken__c.field-meta.xml
<CustomField>
    <fullName>BasicToken__c</fullName>
    <label>Basic: Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/BasicUsername__c.field-meta.xml
<CustomField>
    <fullName>BasicUsername__c</fullName>
    <label>Basic: Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/BearerToken__c.field-meta.xml
<CustomField>
    <fullName>BearerToken__c</fullName>
    <label>Bearer: Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/CalloutType__c.field-meta.xml
<CustomField>
    <fullName>CalloutType__c</fullName>
    <label>CalloutType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard APEX</fullName>
                <default>true</default>
                <label>Standard APEX</label>
            </value>
            <value>
                <fullName>Named Credential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/DefaultHeaders__c.field-meta.xml
<CustomField>
    <fullName>DefaultHeaders__c</fullName>
    <inlineHelpText>JSON based header definition.</inlineHelpText>
    <label>Default Headers</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/DefaultParameters__c.field-meta.xml
<CustomField>
    <fullName>DefaultParameters__c</fullName>
    <inlineHelpText>JSON based URL parameters</inlineHelpText>
    <label>Default Parameters</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <inlineHelpText>For parametarized URL, use the format &lt;parameterName&gt;</inlineHelpText>
    <label>Endpoint</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <defaultValue>&quot;GET&quot;</defaultValue>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/NamedCredentialName__c.field-meta.xml
<CustomField>
    <fullName>NamedCredentialName__c</fullName>
    <inlineHelpText>Api name of the Named credential to be used</inlineHelpText>
    <label>Named Credential: Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/NamedCredentialPath__c.field-meta.xml
<CustomField>
    <fullName>NamedCredentialPath__c</fullName>
    <inlineHelpText>Path to use for the Named credential callout</inlineHelpText>
    <label>Named Credential: Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/OAuthEndpoint__c.field-meta.xml
<CustomField>
    <fullName>OAuthEndpoint__c</fullName>
    <label>OAuth: Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/OAuthMethod__c.field-meta.xml
<CustomField>
    <fullName>OAuthMethod__c</fullName>
    <label>OAuth: Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/RecordLogging__c.field-meta.xml
<CustomField>
    <fullName>RecordLogging__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Logs callout results into the Callout Log sObject. Checking this field will automatically log failed callouts.To log success callouts, use the method logSuccess().</inlineHelpText>
    <label>Record Logging</label>
    <type>Checkbox</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>3</defaultValue>
    <inlineHelpText>The retry callout is run on a Queueable interface. Setting this to a high number may cause your code to hit APEX limitations. It is recommended to set this to a maximum of 2 retries.</inlineHelpText>
    <label>Retry Count</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/RetryOnFail__c.field-meta.xml
<CustomField>
    <fullName>RetryOnFail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retry on Fail</label>
    <type>Checkbox</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/RetryResponseHandler__c.field-meta.xml
<CustomField>
    <fullName>RetryResponseHandler__c</fullName>
    <inlineHelpText>Apex class that implements the Interface CalloutHandler.CalloutResponseHandler. this will handle the response when called via the retry functionality in a Queueable state</inlineHelpText>
    <label>Retry Response Handler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/SimpleToken__c.field-meta.xml
<CustomField>
    <fullName>SimpleToken__c</fullName>
    <label>Simple: Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutLog__c/CalloutLog__c.object-meta.xml
<CustomObject>
    <label>Callout Log</label>
    <nameField>
        <displayFormat>CL{00000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

calloutEngine/force-app/main/default/objects/CalloutLog__c/fields/CalloutSource__c.field-meta.xml
<CustomField>
    <fullName>CalloutSource__c</fullName>
    <label>Callout Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutLog__c/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>Request Body</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutLog__c/fields/RequestHeadersJson__c.field-meta.xml
<CustomField>
    <fullName>RequestHeadersJson__c</fullName>
    <label>Request Headers Json</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutLog__c/fields/RequestMethod__c.field-meta.xml
<CustomField>
    <fullName>RequestMethod__c</fullName>
    <label>Request Method</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutLog__c/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <label>Response Body</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutLog__c/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <label>Response Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutLog__c/fields/ResponseHandler__c.field-meta.xml
<CustomField>
    <fullName>ResponseHandler__c</fullName>
    <label>Response Handler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutLog__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retry</label>
    <type>Checkbox</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutLog__c/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <label>Retry Count</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutLog__c/fields/RetrySource__c.field-meta.xml
<CustomField>
    <fullName>RetrySource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retry Source</label>
    <referenceTo>CalloutLog__c</referenceTo>
    <relationshipLabel>Callout Logs</relationshipLabel>
    <relationshipName>Retries</relationshipName>
    <type>Lookup</type>
</CustomField>

calloutEngine/force-app/main/default/objects/CalloutLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

calloutEngine/force-app/main/default/classes/CalloutEngine.cls
/***********************
 * Class Name: CalloutEngine
 * Author: Kevin Ibalio
 * Purpose: 
************************/

public class CalloutEngine {
    private String calloutKey;
    private String calloutEndpoint;
    private String calloutBody;
    private String calloutMethod;
    private Boolean oAuthPrepared = false;
    private Map<String,String> calloutEndpointParams = new Map<String,String>();
    private Map<String,String> calloutHeaders = new Map<String,String>();
	private CalloutLog__c retrySource;
    private CalloutEngineSetting__mdt setting;
    private HttpRequest callRequest;
    private HttpResponse callResponse;
    
    //Static methods
    public static HttpResponse call(String endpoint, String method, Map<String, String> headers, String body) {
        Http h = new Http();
        HttpRequest request = new HttpRequest();

        if(headers != null) {
            for(String key : headers.keySet()) {
                request.setHeader(key, headers.get(key));
            }
        }
        request.setEndpoint(endPoint);
        request.setMethod(method); 
        if(body != null) request.setBody(body);
        
        HttpResponse response = h.send(request);
        return response;
    }
    
    //Class constructors
    public CalloutEngine(String key) {
        if(key == null || key == '') throw new CalloutEngineException(INVALID_KEY);
        this.calloutKey = key;
        sObject s = MetadataHandler.getData('CalloutEngineSetting__mdt',key);
        if(s == null) {
            throw new CalloutEngineException(key + ' ' + SETTING_NOT_FOUND);
        } else {
            CalloutEngineSetting__mdt chs = (CalloutEngineSetting__mdt) s;
            this.setting = chs;
            this.parseSetting();
        }
    }
    public CalloutEngine(CalloutLog__c retrySrc) {
        this.retrySource = retrySrc;
        if(this.retrySource.CalloutSource__c == null) throw new CalloutEngineException(INVALID_KEY);
        this.calloutKey = this.retrySource.CalloutSource__c;
        sObject s = MetadataHandler.getData('CalloutEngineSetting__mdt',this.calloutKey);
        if(s == null) {
            throw new CalloutEngineException(this.calloutKey + ' ' + SETTING_NOT_FOUND);
        } else {
            CalloutEngineSetting__mdt chs = (CalloutEngineSetting__mdt) s;
            this.setting = chs;
            this.parseSettingFromLog();
        }
    }
    
    //Private methods
    private void parseSetting() {
        this.calloutEndpoint = this.setting.Endpoint__c;
        this.calloutMethod = this.setting.Method__c != null ? this.setting.Method__c : 'GET';
 
        if(this.setting.DefaultParameters__c != null) {
            Map<String, Object> paramsParsed = (Map<String, Object>) JSON.deserializeUntyped(this.setting.DefaultParameters__c);
            for(String s : paramsParsed.keySet()) {
                this.calloutEndpointParams.put(s, String.valueOf(paramsParsed.get(s)));
            }
        }
        
        if(this.setting.DefaultHeaders__c != null) {
            Map<String, Object> paramsParsed = (Map<String, Object>) JSON.deserializeUntyped(this.setting.DefaultHeaders__c);
            for(String s : paramsParsed.keySet()) {
                this.calloutHeaders.put(s, String.valueOf(paramsParsed.get(s)));
            }
        }
    }
    private void parseSettingFromLog() {
        this.calloutEndpoint = this.retrySource.Endpoint__c;
        this.calloutMethod = this.retrySource.RequestMethod__c != null ? this.retrySource.RequestMethod__c : 'GET';
        this.calloutEndpointParams = new Map<String,String>();
        if(this.retrySource.RequestHeadersJson__c != null) {
            Map<String, Object> paramsParsed = (Map<String, Object>) JSON.deserializeUntyped(this.retrySource.RequestHeadersJson__c);
            for(String s : paramsParsed.keySet()) this.calloutHeaders.put(s, String.valueOf(paramsParsed.get(s)));
        }
        this.calloutBody = this.retrySource.RequestBody__c;
    }
    private void rebuildEndpoint() {
        if(this.setting.CalloutType__c == 'Named Credential') {
            this.calloutEndpoint = 'callout:' + this.setting.NamedCredentialName__c + (this.setting.NamedCredentialPath__c != null ? this.setting.NamedCredentialPath__c : '');
        } else {
            List<String> urlParams = new List<String>();
            for(String s : this.calloutEndpointParams.keySet()) {
                String finder = '<' + s + '>';
                if(this.calloutEndpoint.indexOf(finder) > -1) this.calloutEndpoint = this.calloutEndpoint.replaceAll(finder, this.calloutEndpointParams.get(s));
                else urlParams.add(s + '=' + this.calloutEndpointParams.get(s));
            }
            if(!urlParams.isEmpty()) this.calloutEndpoint += (this.calloutEndpoint.indexOf('?') > -1 ? '&' : '?') + String.join(urlParams, '&');
        }
    }
    private void addAuth(HttpRequest hr) {
        switch on this.setting.AuthenticationType__c {
            when 'Simple' { this.handleSimple(); }
            when 'API Key' { this.handleApiKey(); }
            when 'Basic' { this.handleBasic(); }
            when 'Bearer' { this.handleBearer(); }
            when 'OAuth' { this.handleOAuth(); }
            when else { /* do nothing */ }
        }
    }
    private void handleSimple() {
        this.calloutHeaders.put('Authorization', this.setting.SimpleToken__c);
    }
    private void handleApiKey() {
        switch on this.setting.APIKeyTokenPlacement__c {
            when 'Endpoint' {
                this.calloutEndpointParams.put('api_key', this.setting.APIKeyToken__c);
            }
            when 'Header' {
                this.calloutHeaders.put('X-API-Key', this.setting.APIKeyToken__c);
            }
            when 'Both' {
                this.calloutEndpointParams.put('api_key', this.setting.APIKeyToken__c);
                this.calloutHeaders.put('X-API-Key', this.setting.APIKeyToken__c);
            }
            when null {
                this.calloutHeaders.put('X-API-Key', this.setting.APIKeyToken__c);
            }
        }
    }
    private void handleBasic() {
        if(this.setting.BasicToken__c == null) {
            Blob headerValue = Blob.valueOf(this.setting.BasicUsername__c + ':' + this.setting.BasicPassword__c);
            this.setting.BasicToken__c = EncodingUtil.base64Encode(headerValue);
        }
        this.calloutHeaders.put('Authorization', 'Basic ' + this.setting.BasicToken__c);
    }
    private void handleBearer() {
        this.calloutHeaders.put('Authorization', 'Bearer ' + this.setting.BearerToken__c);
    }
    private void handleOAuth() {
        if(!this.oAuthPrepared) throw new CalloutEngineException('For OAuth callouts, please call the [HttpResponse prepareOAuth()] method first');
    }
    private CalloutLog__c createLog(Boolean isSuccess, Boolean retry, Integer retrycount) {
        return new CalloutLog__c(
        	Status__c = isSuccess ? 'Success' : 'Failed',
            Endpoint__c = this.calloutEndpoint,
            RequestBody__c = this.calloutBody,
            RequestHeadersJson__c = JSON.serialize(this.calloutHeaders),
            RequestMethod__c = this.calloutMethod,
            RetryCount__c = retryCount,
            RetrySource__c = this.retrySource == null? null : this.retrySource.Id,
            CalloutSource__c = this.calloutKey,
            ResponseHandler__c = this.setting.RetryResponseHandler__c,
            ResponseCode__c = String.valueOf(this.callResponse.getStatusCode()),
            ResponseBody__c = this.callResponse.getBody(),
            Retry__c = retry
        );
    }
    
    //public methods
    public void setBody(String calloutBody) {
        this.calloutBody = calloutBody;
    }
    public void setEndpointParams(Map<String,String> endpointValues) {
        for(String s : endpointValues.keySet()) this.calloutEndpointParams.put(s, endpointValues.get(s));
    }
    public void setEndpointParam(String key,String value) {
        this.calloutEndpointParams.put(key, value);
    }
    public void setHeaders(Map<String,String> headerValues) {
        for(String s : headerValues.keySet()) this.calloutHeaders.put(s, headerValues.get(s));
    }
    public void setHeader(String key, String value) {
        this.calloutHeaders.put(key, value);
    }
    public void overrideHeader(Map<String, String> headers) {
        for(String s : headers.keySet()) this.calloutHeaders.put(s, headers.get(s));
    }
    public HttpResponse prepareOAuth() {
        this.oAuthPrepared = true;
        return call(this.setting.OAuthEndpoint__c,
            this.setting.OAuthMethod__c,
            new Map<String,String>(),null);
    }
    public Object call(String body) {
        this.setBody(body);
        return this.call();
    }
    public Object call() {
        Http h = new Http();
        HttpRequest hr = new HttpRequest();
        
        this.addAuth(hr);
        if(this.retrySource == null) this.rebuildEndpoint();
        
        hr.setEndpoint(this.calloutEndpoint);
        hr.setMethod(this.calloutMethod);
        
        if(this.calloutBody != null) hr.setBody(this.calloutBody);
        for(String s : this.calloutHeaders.keySet()) hr.setHeader(s, this.calloutHeaders.get(s));
        
        HttpResponse response = h.send(hr);
        this.callRequest = hr;
        this.callResponse = response;
        return response.getBody();
    }
    public HttpResponse getResponse() {
        return this.callResponse;
    }
    public void markFailed() {
        this.markFailed(false);
    }
    public void markFailed(Boolean queueLogCreate) {
        if(this.setting.RecordLogging__c) {
            if(this.setting.RetryCount__c == null) this.setting.RetryCount__c = 1; 
            Integer retryCount = this.retrySource == null ? 0 : (Integer.valueOf(this.retrySource.RetryCount__c) + 1);
            Boolean retry = this.setting.RetryOnFail__c && this.setting.RetryCount__c >= retryCount;
            CalloutLog__c cl = this.createLog(false, retry, retryCount);
            
            if(queueLogCreate) {
                System.enqueueJob(new CalloutLogCreate(cl));
            } else {
                insert cl;
                if(retry) System.enqueueJob(new CalloutRetryHandler(cl));
            }
            
        }
    }
    public void logSuccess() {
        Integer retryCount = this.retrySource == null ? 0 : (Integer.valueOf(this.retrySource.RetryCount__c) + 1);
        insert this.createLog(true,false,null);
    }

    //Inner Classes and Interfaces
    public class CalloutLogCreate implements Queueable {
        public CalloutLog__c log;
        public Boolean retry = false;
        public CalloutLogCreate(CalloutLog__c log) {
            this.log = log;
        }
        public void execute(QueueableContext context) {
            insert this.log;
            if(this.log.Retry__c) System.enqueueJob(new CalloutRetryHandler(this.log));
        }
    }
    public class CalloutRetryHandler implements Queueable, Database.AllowsCallouts {
        public CalloutLog__c log;
        public CalloutRetryHandler(CalloutLog__c log) {
            this.log = log;
        }
        public void execute(QueueableContext context) {
            Type t = Type.forName(this.log.ResponseHandler__c);
            CalloutResponseHandler crh = (CalloutResponseHandler) t.newInstance();
            CalloutEngine ch = new CalloutEngine(this.log);
            ch.call();
            crh.handleResponse(ch);
        }
    }
    private class CalloutEngineException extends Exception {}
    public interface CalloutResponseHandler {
        Map<String,Object> handleResponse(CalloutEngine ch);
    }
    
    //Messaging attributes
    private static final String SETTING_NOT_FOUND = 'callout setting not found in the Custom Metadata';
    private static final String INVALID_KEY = 'The callout key provided is invalid';
}