calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/CalloutEngineSetting__mdt.object-meta.xml
<CustomObject>
    <label>Callout Engine Setting</label>
    <pluralLabel>Callout Engine Settings</pluralLabel>
</CustomObject>

calloutEngine/force-app/main/default/objects/CalloutEngineSetting__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <defaultValue>&quot;GET&quot;</defaultValue>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

calloutEngine/force-app/main/default/classes/CalloutEngineTest.cls
@isTest
public class CalloutEngineTest {
    @isTest
    public static void testBasic() {
        CalloutEngine calloutRun = new CalloutEngine('TEST_Basic');
        calloutRun.setEndpointParam('test1','asd');
        calloutRun.setEndpointParam('test2','asd');
        calloutRun.setMock('{"test":"test"}');
        
        Test.startTest();
        calloutRun.call();
        calloutRun.logSuccess();
        calloutRun.markFailed();
        Test.stopTest();
        
    }
    
    @isTest
    public static void testSimple() {
        CalloutEngine calloutRun = new CalloutEngine('TEST_Simple');
        Map<String,String> epParams = new Map<String,String>();
        epParams.put('test1','asd');
        epParams.put('test2','asd');
        calloutRun.setEndpointParams(epParams);
        calloutRun.setMock(200,'{"test":"test"}');
        
        Test.startTest();
        calloutRun.call();
        Test.stopTest();
    }
    
    @isTest
    public static void testBearer() {
        CalloutEngine calloutRun = new CalloutEngine('TEST_Bearer');
        Map<String,String> headParams = new Map<String,String>();
        headParams.put('test1','asd');
        calloutRun.setHeaders(headParams);
        calloutRun.setHeader('test2','asd');
        calloutRun.setBody('{"test":"test"}');
        calloutRun.setMock(200,'{"test":"test"}');
        
        Test.startTest();
        calloutRun.call();
        Test.stopTest();
    }
    
    @isTest
    public static void testAPIKey() {
        CalloutEngine calloutRun = new CalloutEngine('TEST_APIKey');
        calloutRun.setMock(200,'{"test":"test"}');
        
        Test.startTest();
        calloutRun.call();
        Test.stopTest();
    }
    @isTest
    public static void testOAuth() {
        CalloutEngine calloutRun = new CalloutEngine('TEST_OAuth');
        Map<String,String> headParams = new Map<String,String>();
        headParams.put('test1','asd');
        calloutRun.setHeaders(headParams);
        calloutRun.setHeader('test2','asd');
        calloutRun.setBody('{"test":"test"}');
        calloutRun.setMockOAuth('{"access_token":"12345"}');
        calloutRun.setMock(200,'{"test":"test"}');
        
        Test.startTest();
        calloutRun.call('{"test":"test"}');
        Test.stopTest();
    }
    
    @isTest
    public static void testBaseCall() {
        Test.setMock(HttpCalloutMock.class, new CalloutEngine.CalloutEngineMock('{"a":"a"}',200));
        Test.startTest();
        CalloutEngine.call('www.test.com','GET',new Map<String,String>(),'{"a":"a"}');
        Test.stopTest();
    }
    @isTest
    public static void metadataTest() {
        Map<String,Object> fieldsToAdd = new Map<String,Object>();
        fieldsToAdd.put('Method__c','PUT');
        MetadataHandler.createUpdateMetadata('CalloutEngineSetting__mdt','TEST_OAuth',fieldsToAdd);
    }
}